In [ ]:
import pandas as pd
import numpy as np
import sys
sys.path.append( 'C:\Machine Learning\mylib' )
import LassoRegression as LS
df = pd.read_csv('../datasets/trip_duration_task_pred.csv')
df1 = df.head(10000)
y = df1["trip_duration"]
X = df1.drop(["trip_duration"], axis=1)
df1

: 

Моя регрессия лассо и метрики

In [3]:
data = {'Height': [1.52, 1.57, 1.63, 1.68, 1.73, 1.78, 1.83, 1.88, 1.93, 1.98], 'Weight': [52, 57, 63, 68, 75, 82, 89, 97, 105, 113]} 
df = pd.DataFrame(data)
y1 = df["Weight"]
X1 =  df.drop(["Weight"], axis=1)
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.2)


In [32]:
m = LS.LassoRegressionModel(0.05, 1000, 0.5).Train(X_train1, y_train1)
predict_y = m.LassoRegressionPredict(X_test1)
print(predict_y)
print(y_test1)

[67.94648848 57.06205145]
4    75
2    63
Name: Weight, dtype: int64


In [5]:
print(LS.MAE(y_test1, predict_y))
print(LS.MSE(y_test1, predict_y))
print(LS.RMSE(y_test1, predict_y))
print(LS.MAPE(y_test1, predict_y))
print(LS.R2(y_test1, predict_y))

6.49573003688846
42.50562889475235
6.519634107429063
0.09414998595728379
0.9828882331341576


Библиотечные модели

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression().fit(X_train, y_train)

In [9]:
y_pred = lr.predict(X_test)
y_pred

array([2788.99999977, 1102.99999977,  193.99999977, ...,  421.99999977,
        420.99999977,  224.99999977])

In [10]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lr.score(X_test, y_test)}')

MAE: 2.3460394402263773e-07
MSE: 5.50390105509816e-14
RMSE: 2.3460394402264769e-07
MAPE: 2.3438079691630758e-05
R^2: 1.0


In [11]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
alpha = {"alpha":np.arange(0.1, 1, 0.1)}
ridge = RandomizedSearchCV(Ridge(), alpha,scoring= 'neg_mean_absolute_percentage_error').fit(X_train, y_train)
a_ridge = ridge.best_params_['alpha']

C:\Machine Learning\venv\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.06142e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.02284e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.07483e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge

C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.30298e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.26121e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.3178e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.29217e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216

In [12]:
ridge = Ridge(alpha=a_ridge).fit(X_train, y_train)
y_pred1 = ridge.predict(X_test)
y_pred1

C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.13214e-35): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


array([2789.00000171, 1103.00000003,  193.99999888, ...,  421.99999952,
        420.99999906,  224.99999885])

In [13]:
print(f'MAE: {mean_absolute_error(y_test, y_pred1)}')
print(f'MSE: {mean_squared_error(y_test, y_pred1)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred1))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred1))}')
print(f'R^2: {ridge.score(X_test, y_test)}')

MAE: 7.050457468364968e-07
MSE: 6.611200994245977e-12
RMSE: 2.571225582138988e-06
MAPE: 4.54596234421829e-05
R^2: 1.0


In [17]:
lasso = RandomizedSearchCV(Lasso(), alpha, scoring= 'neg_mean_absolute_percentage_error').fit(X_train, y_train)
a_lasso = lasso.best_params_['alpha']
lasso = Lasso(alpha=a_lasso).fit(X_train, y_train)
y_pred2 = lasso.predict(X_test)
y_pred2

C:\Machine Learning\venv\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.195e+10, tolerance: 6.490e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.137e+10, tolerance: 4.378e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_m

C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.198e+10, tolerance: 6.482e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.042e+10, tolerance: 6.168e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.200e+10, toleranc

array([1374.5257906 ,  809.95314198,  945.62639574, ...,  650.23445891,
        985.08647574, 1012.27920507])

In [18]:
print(f'MAE: {mean_absolute_error(y_test, y_pred2)}')
print(f'MSE: {mean_squared_error(y_test, y_pred2)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred2))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred2))}')
print(f'R^2: {lasso.score(X_test, y_test)}')

MAE: 495.267728755155
MSE: 3873692.166363228
RMSE: 1968.1697503933008
MAPE: 1.1625946150339463
R^2: 0.018420486981758355


In [19]:
from sklearn.preprocessing import PolynomialFeatures
p = PolynomialFeatures(2)  
X_train_p=p.fit_transform(X_train) 
X_test_p=p.fit_transform(X_test) 

In [20]:
lr2=LinearRegression().fit(X_train_p, y_train)
lr2_pred = lr2.predict(X_test_p)

In [21]:
print(f'MAE: {mean_absolute_error(y_test, lr2_pred )}')
print(f'MSE: {mean_squared_error(y_test, lr2_pred )}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, lr2_pred ))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, lr2_pred ))}')
print(f'R^2: {lr2.score(X_test_p, y_test)}')

MAE: 1.670511559692372
MSE: 88.98674295728439
RMSE: 9.433278484031115
MAPE: 0.061345140758100644
R^2: 0.999977451082826


In [22]:
lasso2 = RandomizedSearchCV(Lasso(), alpha, scoring= 'neg_mean_absolute_percentage_error').fit(X_train_p, y_train)
a_lasso2 = lasso2.best_params_['alpha']
lasso2 = Lasso(alpha=a_lasso2).fit(X_train_p, y_train)
lasso2_pred = lasso2.predict(X_test_p)

C:\Machine Learning\venv\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.188e+10, tolerance: 6.490e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.132e+10, tolerance: 4.378e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_m

C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.188e+10, tolerance: 6.482e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.029e+10, tolerance: 6.168e+06
  model = cd_fast.enet_coordinate_descent(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.188e+10, toleranc

In [23]:
print(f'MAE: {mean_absolute_error(y_test, lasso2_pred )}')
print(f'MSE: {mean_squared_error(y_test, lasso2_pred )}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, lasso2_pred ))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, lasso2_pred ))}')
print(f'R^2: {lasso2.score(X_test_p, y_test)}')

MAE: 495.0870977000404
MSE: 3881640.3125090953
RMSE: 1970.1878876160758
MAPE: 1.1613012426008622
R^2: 0.01640645564209653


In [24]:
ridge2 = RandomizedSearchCV(Ridge(), alpha, scoring= 'neg_mean_absolute_percentage_error').fit(X_train_p, y_train)
a_ridge2 = ridge2.best_params_['alpha']
ridge2 = Ridge(alpha=a_ridge2).fit(X_train_p, y_train)
ridge2_pred = ridge2.predict(X_test_p)

C:\Machine Learning\venv\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.06715e-74): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.01788e-74): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.09553e-74): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Machine Learning\venv\lib\site-packages\sklearn\linear_model\_ridge

In [25]:
print(f'MAE: {mean_absolute_error(y_test, ridge2_pred )}')
print(f'MSE: {mean_squared_error(y_test, ridge2_pred )}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, ridge2_pred ))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, ridge2_pred ))}')
print(f'R^2: {lr2.score(X_test_p, y_test)}')

MAE: 6.687320736633299
MSE: 149.3617689056842
RMSE: 12.221365263573631
MAPE: 0.11038762388211673
R^2: 0.999977451082826
